# Generated by Django 2.2.24 on 2022-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
